apiVersion: v1
kind: ConfigMap
metadata:
  name: quickhire-config
  namespace: quickhire
data:
  MONGODB_URI: "mongodb://mongo:27017/quick-hire"
  JWT_ACCESS_EXPIRES: "15m"
  JWT_REFRESH_EXPIRES: "7d"
  PORT: "3000"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://34.200.218.39:30021/api"
