apiVersion: v1
kind: Secret
metadata:
  name: quickhire-secrets
  namespace: quickhire
type: Opaque
stringData:
  JWT_ACCESS_SECRET: "dev-access-secret-min-32-characters-long"
  JWT_REFRESH_SECRET: "dev-refresh-secret-different-from-access"
